### ISSUE TITLE
vdjtools installation problem on macOS MOjave

### ISSUE THREAD

**Issue by sumanta-barman** [mikessh/homebrew-repseq#5]
Hello,

I wanted to install vdjtools on macOS MOjave. Then it showed following error. 

==> Installing vdjtools from mikessh/repseq
==> Downloading https://github.com/mikessh/vdjtools/releases/download/1.2.1/vdjtools-1.2.1.zip
Already downloaded: /Users/Sumanta.Barman/Library/Caches/Homebrew/downloads/2bfaacb2fc90ef908cae13fb3c7a646c00da682b21071ca90c11b830c054031e--vdjtools-1.2.1.zip
==> /usr/local/Cellar/vdjtools/1.2.1/bin/vdjtools RInstall
Last 15 lines from /Users/Sumanta.Barman/Library/Logs/Homebrew/vdjtools/01.vdjtools:
2019-06-18 12:56:27 +0200

/usr/local/Cellar/vdjtools/1.2.1/bin/vdjtools
RInstall

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/mikessh/homebrew-repseq/issues

Then I used the direct vdjtools-1.2.1.jar file to run the program and installed R packages (java -jar vdjtools.jar Rinstall). But "ape" and "gplots" packages  are failed to install and shows following error. 

[RUtil] Executing Rscript test.r reshape2 FField reshape gplots gridExtra circlize ggplot2 grid VennDiagram RColorBrewer plotrix ape MASS scales
[1] "FAILED to install  gplots"
[1] "FAILED to install  ape"
[RInstall] Finished

So I can't visualize all data. Afterward, I installed that two packages manually by running the command in R. But when I run TrackClonotypes command, then it still cannot find gplots so cannot generate all visualization file and shows following error.

[ERROR] Loading required package: gplots
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘gplots’
Error in heatmap.2(x, labRow = df$cdr3aa, labCol = t, Colv = FALSE, dendrogram = "row",  : 
  could not find function "heatmap.2"
Execution halted

Could be you please help how I can solve this problem?

**Comment by sharonov** [comment]
@sumanta-barman 
Have you succeed with VDJTools installation?

I have the same issue.

**Comment by sophiamaedler** [comment]
Any updates on this? I am also having a similar issue.

**Comment by sharonov** [comment]
> Any updates on this? I am also having a similar issue.

No, I'm just using by calling jar file like:
java -jar ~/p/vdjtools-1.2.1/vdjtools.jar CalcDiversityStats -m ./metadata.txt

**Comment by ampmartinez** [comment]
Hello,
I am facing the same problem in the installation. Besides, when I try to call the jar file, I obtain an java.lang.NoClassDefFoundError error. 
Any clue about how to solve it? I would really appreciate it. Thanks!

**Comment by sumanta-barman** [comment]
Hi, it's still not working. But you can download the file from here...https://milaboratory.com/software/vdjtools/
This works perfectly for me.

**Comment by sumanta-barman** [comment]
> @sumanta-barman
> Have you succeed with VDJTools installation?
> 
> I have the same issue.
Hi,
Last week I reinstalled the java -jar vdjtools.jar Rinstall. Now all problems are resolved. BTW Now I'm using mac OS Catalina.

**Comment by sumanta-barman** [comment]
> @sumanta-barman
> Have you succeed with VDJTools installation?
> 
> I have the same issue.

Hi,
Last week I reinstalled the java -jar vdjtools.jar Rinstall. Now all problems are resolved. BTW Now I'm using mac OS Catalina.

**Comment by ampmartinez** [comment]
> Hi, it's still not working. But you can download the file from here...https://milaboratory.com/software/vdjtools/
> This works perfectly for me.

Thanks for your reply. However for me it is still not working. When I try to run the program I get:

`java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
(...)
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache     
(...)`

I suppose it is for the java version (?). I have unsuccessfully tried again after reinstalling JDK and JRE.
I am still trying to solve it... 

`java version "14.0.1" 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)`

**Comment by sharonov** [comment]
Try to convert your files first with Convert function from vdjtools

**Comment by ampmartinez** [comment]
> rst with Convert function from vdjtools

Hi,
Convert function doesn't work neither..
Even when I use no functions, `$ java -jar vdjtools-1.2.1.jar` I obtain this full message: 
`java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
	at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
	at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:109)
	at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
	at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:207)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:105)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:83)
	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
	at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:427)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:67)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:64)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:64)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:161)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at com.antigenomics.vdjtools.VdjTools.main(VdjTools.groovy)
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
	at org.codehaus.groovy.runtime.dgmimpl.NumberNumberMetaMethod.<clinit>(NumberNumberMetaMethod.java:33)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:124)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:346)
	at java.base/java.lang.Class.newInstance(Class.java:604)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.createMetaMethodFromClass(MetaClassRegistryImpl.java:255)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:108)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:83)
	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
	at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:427)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:67)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:64)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:64)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:161)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at com.antigenomics.vdjtools.VdjTools.main(VdjTools.groovy)`

I believe that with no arguments the program should give me a list of possible actions, (maybe it is not true) but instead I obtain this error..

**Comment by yilmazbah** [comment]
Did you find any solution ampmartinez?

**Comment by yilmazbah** [comment]
> > rst with Convert function from vdjtools
> 
> Hi,
> Convert function doesn't work neither..
> Even when I use no functions, `$ java -jar vdjtools-1.2.1.jar` I obtain this full message:
> `java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7 at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43) at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35) at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:109) at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95) at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39) at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:207) at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:105) at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:83) at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36) at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:427) at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:67) at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:64) at java.base/java.security.AccessController.doPrivileged(AccessController.java:312) at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:64) at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:161) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136) at com.antigenomics.vdjtools.VdjTools.main(VdjTools.groovy) Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache at org.codehaus.groovy.runtime.dgmimpl.NumberNumberMetaMethod.<clinit>(NumberNumberMetaMethod.java:33) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:124) at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:346) at java.base/java.lang.Class.newInstance(Class.java:604) at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.createMetaMethodFromClass(MetaClassRegistryImpl.java:255) at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:108) at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:83) at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36) at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:427) at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:67) at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:64) at java.base/java.security.AccessController.doPrivileged(AccessController.java:312) at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:64) at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:161) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136) at com.antigenomics.vdjtools.VdjTools.main(VdjTools.groovy)`
> 
> I believe that with no arguments the program should give me a list of possible actions, (maybe it is not true) but instead I obtain this error..

Did you find any solution ampmartinez?

**Comment by rodrigarc** [comment]
> > rst with Convert function from vdjtools
> 
> Hi,
> Convert function doesn't work neither..
> Even when I use no functions, `$ java -jar vdjtools-1.2.1.jar` I obtain this full message:
> `java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7 at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43) at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35) at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:109) at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95) at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39) at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:207) at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:105) at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:83) at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36) at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:427) at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:67) at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:64) at java.base/java.security.AccessController.doPrivileged(AccessController.java:312) at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:64) at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:161) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136) at com.antigenomics.vdjtools.VdjTools.main(VdjTools.groovy) Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache at org.codehaus.groovy.runtime.dgmimpl.NumberNumberMetaMethod.<clinit>(NumberNumberMetaMethod.java:33) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:124) at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:346) at java.base/java.lang.Class.newInstance(Class.java:604) at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.createMetaMethodFromClass(MetaClassRegistryImpl.java:255) at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:108) at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:83) at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36) at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:427) at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:67) at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:64) at java.base/java.security.AccessController.doPrivileged(AccessController.java:312) at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:64) at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:161) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136) at com.antigenomics.vdjtools.VdjTools.main(VdjTools.groovy)`
> 
> I believe that with no arguments the program should give me a list of possible actions, (maybe it is not true) but instead I obtain this error..

I have the same error. Any updates?

**Comment by rethavathij** [comment]
I had the same error java.lang.NoClassDefFoundError while using Java14 . 
Changing the Java version and JAVA_HOME path worked.

Use the command $ `/usr/libexec/java_home -V `to check the java version 
> #Matching Java Virtual Machines (3):
>     14.0.2 (x86_64) "Oracle Corporation" - "Java SE 14.0.2" /Library/Java/JavaVirtualMachines/jdk-14.0.2.jdk/Contents/Home

Install Java SE 8 from this link [https://www.oracle.com/java/technologies/javase/javase8-archive-downloads.html](url)
and upgrade Gradle version 6.2 to 7.2 
$ `brew upgrade gradle`

Specify the JAVA_HOME in the $ `open ~/.bash_profile` using the command based on the version downloaded. e.g:
$ `export JAVA_HOME=$(/usr/libexec/java_home -v1.8.0_202)` and that'll link the desired JVM to your JAVA command.

Then source ~/.bash_profile after saving and run the $ `java -jar vdjtools-1.2.1.jar`
